name: google_maps_widget
description: A Flutter package which can be used to make polylines(route) from a source to a destination, and also handle a driver's realtime location (if any) on the map.
version: 1.0.5+1
homepage: https://github.com/rithik-dev/google_maps_widget

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_lints: ^2.0.1
